export const SUCCESS = "SUCCESS"
export const FAILED = "FAILED"

export const UPDATE_MESSAGE = "UPDATE_MESSAGE"

export const USERNAME_CAN_USE = "USERNAME_CAN_USE"
export const USERNAME_CAN_NOT_USE = "USERNAME_CAN_NOT_USE"



export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILED = "USER_LOGIN_SUCCESS"

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED"


export const VERIFY_VERCODE_SUCCESS = "VERIFY_VERCODE_SUCCESS"
export const VERIFY_VERCODE_FAILED = "VERIFY_VERCODE_FAILED"